## Simulating data

#+begin_src R :exports code :results silent
  set.seed(2021) # RNG seed: arbitrary integer value
  parents <- rnorm(n = 50, mean = 480, sd = 40)
#+end_src

#+begin_src R :exports results :results output
  parents
#+end_src

#+RESULTS:
:  [1] 495.0789 492.0619 436.0791 434.7838 368.1386 508.8229
:  [7] 517.5648 470.8249 550.3653 484.6947 445.8751 516.3704
: [13] 527.8549 465.1366 475.0696 552.0017 548.1598 358.4494
: [19] 388.4410 482.3321 566.9746 523.9273 492.7288 477.0741
: [25] 513.3707 487.9500 531.9137 517.4687 474.1027 484.4173
: [31] 447.4998 450.2519 523.8138 577.4149 495.5247 491.6251
: [37] 468.5761 483.0406 457.5881 497.8875 516.3400 459.7976
: [43] 467.9598 450.9586 432.7969 490.1230 465.1715 480.8872
: [49] 506.4018 499.5517

#+begin_src R :exports code
  control <- rnorm(n = 50, mean = 500, sd = 40)
#+end_src

** \(t\)-test

#+begin_src R :exports both :results output
  t.test(parents, control, var.equal = TRUE)
#+end_src

#+RESULTS:
#+begin_example

	Two Sample t-test

data:  parents and control
t = -2.0738, df = 98, p-value = 0.04072
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -36.5195723  -0.8035714
sample estimates:
mean of x mean of y 
 485.0249  503.6865
#+end_example

** ANOVA

#+begin_src R :exports none :results silent
  dat <- tibble(
    group = rep(c("parent", "control"), 
		c(length(parents), length(control))),
    rt = c(parents, control))
#+end_src

#+begin_src R :exports both :results output
  summary(aov(rt ~ group, dat))    
#+end_src

#+RESULTS:
:             Df Sum Sq Mean Sq F value Pr(>F)  
: group        1   8706    8706     4.3 0.0407 *
: Residuals   98 198401    2024                 
: ---
: codes:  
: 0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

** Regression

\(Y_i = \beta_0 + \beta_1 X_i + e_i\)

\(e_i \sim N(0, \sigma^2)\)

** Regression

#+begin_src R :exports both :results output
  summary(lm(rt ~ group, dat))
#+end_src

#+RESULTS:
#+begin_example

Call:
lm(formula = rt ~ group, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-126.575  -26.632    1.113   24.885  124.379 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  503.686      6.363  79.156   <2e-16 ***
groupparent  -18.662      8.999  -2.074   0.0407 *  
---
codes:  
0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 44.99 on 98 degrees of freedom
Multiple R-squared:  0.04204,	Adjusted R-squared:  0.03226 
F-statistic:   4.3 on 1 and 98 DF,  p-value: 0.04072
#+end_example

** 

#+REVEAL_HTML: <a href="https://shiny.psy.gla.ac.uk/Dale/GLM">GLM shiny app</a>

* Single- vs Multi-level

#+REVEAL_HTML: <div class="column" style="float:left; width: 50%">
#+begin_src R :exports results :results value :colnames yes
  tibble(sub = 1:6,
	 A = rep(c("A1", "A2"), each = 3),
	 Y = round(rnorm(6, 800, 100)))
#+end_src

#+RESULTS:
| subj_id | A  |   Y |
|---------+----+-----|
|       1 | A1 | 794 |
|       2 | A1 | 718 |
|       3 | A1 | 711 |
|       4 | A2 | 607 |
|       5 | A2 | 822 |
|       6 | A2 | 855 |

#+REVEAL_HTML: </div>

#+REVEAL_HTML: <div class="column" style="float:right; width: 50%">
#+begin_src R :exports results :results value :colnames yes
  tibble(sub = rep(1:2, each = 3),
         stim = rep(LETTERS[1:3], 2),
	 A = rep(c("A1", "A2"), each = 3),
	 Y = round(rnorm(6, 800, 100)))
#+end_src

#+RESULTS:
| sub | stim | A  |   Y |
|-----+------+----+-----|
|   1 | A    | A1 | 975 |
|   1 | B    | A1 | 765 |
|   1 | C    | A1 | 702 |
|   2 | A    | A2 | 972 |
|   2 | B    | A2 | 610 |
|   2 | C    | A2 | 954 |

#+REVEAL_HTML: </div>

** Issues with multi-level data

- GLMs assume independence of residuals
- Observations within a cluster (unit) are not independent
- Any sources of non-independence must be modeled (we'll learn this later!) or aggregated away
- Typical consequence of failing to do so: High false positives

* Regression: Killer App

|------------------+--------+-------+------------|
| technique        | t-test | ANOVA | regression |
|------------------+--------+-------+------------|
| Categorical IVs  | ✓      | ✓     | ✓          |
| Continuous DVs   | ✓      | ✓     | ✓          |
| Continuous IVs   |        | -     | ✓          |
| Multi-level data | -      | -     | ✓          |
| Categorical DVs  |        |       | ✓          |
| Unbalanced data  | -      | -     | ✓          |
| >1 sampling unit |        |       | ✓          |

** 4 functions to rule them all

1. Is the data single- or multi-level?
2. Is the response continuous or discrete?
3. How are the observations distributed?

#+REVEAL_HTML: <br/><br/>

| structure | response  | distrib | R fnc           |
|-----------+-----------+---------+-----------------|
| single    | cont      | normal  | =base::lm()=    |
| single    | cont/disc | various | =base::glm()=   |
| multi     | cont      | normal  | =lme4::lmer()=  |
| multi     | cont/disc | various | =lme4::glmer()= |

* Course structure

- Weekly in-person lectures
- Weekly textbook readings
  https://psyteachr.github.io/stat-models
- Weekly formative assignments

** Summative Assessment

Final exam, in a computer lab with invigilators

#+begin_center
/see "assessment and feedback" documents for more info/
#+end_center

** For next week

1. install or update R/RStudio
   - R 4.2.1
   - RStudio 2022.07.1 Build 554+
2. read Chapters 1 and 2 of the [[https://psyteachr.github.io/stat-models][textbook]]
3. attempt formative assignment 1

[[https://talklab.psy.gla.ac.uk/stat-models]]
